# Generated by Django 4.2.7 on 2023-11-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAPI', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='order_time',
            field=models.DateField(auto_now=True),
        ),
    ]
