# Generated by Django 4.2.7 on 2023-11-27 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAPI', '0004_alter_logger_order_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logger',
            name='phone',
        ),
    ]
