# Generated by Django 4.2.7 on 2023-11-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAPI', '0006_category_logger_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
