# Generated by Django 4.2.7 on 2023-11-27 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAPI', '0008_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Place',
        ),
    ]
